name: easyvizar-map
base: core22
version: "0.1"
summary: Manager for 3D mapping data
description: |
  This module automatically merges 3D mapping data and
  other sensor data that is uploaded to the EasyVizAR
  edge server.

grade: stable
confinement: strict

apps:
  detect:
    command: bin/map
    daemon: simple
    environment:
      CACHE_DIR: $SNAP_DATA/cache
      DATA_PATH: $SNAP/easyvizar
      EASYVIZAR_SERVER: "http://localhost:5000"
      PYTHONPATH: $SNAP_DATA/lib/python3.10/site-packages
    plugs:
      - network

architectures:
  - build-on: amd64
  - build-on: arm64

hooks:
  install:
    plugs: [network]
  post-refresh:
    plugs: [network]

parts:
  map:
    plugin: python
    source: .
    build-packages:
      - python3-dev
    stage-packages:
      - python3
      - python3-pip
    python-requirements:
      - requirements.txt

plugs:
  data:
    interface: content
    content: data
    target: $SNAP/easyvizar
    default-provider: easyvizar-edge
